# -*- coding: utf-8 -*-
"""Untitled22.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1odavd9iRZKx2050-M0BODpNBeR6-cFY5
"""

# Import required libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Display all columns when printing DataFrames
pd.set_option('display.max_columns', None)

print("Libraries imported successfully!")

# Upload the dataset from your computer

from google.colab import files

uploaded = files.upload()

# Read the uploaded CSV file

df = pd.read_csv("final_dav_dataset (1).csv")

print("Dataset loaded successfully!")

# -------------------------------
# DATASET PROFILE
# -------------------------------

print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

print("\nColumn names:")
print(df.columns.tolist())

print("\nData types:")
print(df.dtypes)

print("\nFirst 5 records:")
display(df.head())

print("\nLast 5 records:")
display(df.tail())

print("\nDataset information:")
df.info()

# -------------------------------
# SUMMARY STATISTICS
# -------------------------------

print("Summary statistics:")
display(df.describe())

print("\nSummary including categorical columns:")
display(df.describe(include='all'))

# -------------------------------
# DUPLICATE DETECTION
# -------------------------------

duplicate_count = df.duplicated().sum()

print("Number of duplicate rows:", duplicate_count)

# -------------------------------
# REMOVE DUPLICATES
# -------------------------------

df = df.drop_duplicates()

print("Dataset shape after removing duplicates:", df.shape)

# -------------------------------
# MISSING VALUE CHECK
# -------------------------------

print("Missing values in each column:")

missing_values = df.isnull().sum()

display(missing_values)

# -------------------------------
# MISSING VALUE COUNT & PERCENTAGE
# -------------------------------

missing_count = df.isnull().sum()

missing_percentage = (df.isnull().sum() / len(df)) * 100

missing_summary = pd.DataFrame({
    'Missing Count': missing_count,
    'Missing Percentage': missing_percentage
})

display(missing_summary)

# -------------------------------
# IDENTIFY COLUMN TYPES
# -------------------------------

numerical_columns = df.select_dtypes(include=np.number).columns.tolist()

categorical_columns = df.select_dtypes(include='object').columns.tolist()

print("Numerical columns:")
print(numerical_columns)

print("\nCategorical columns:")
print(categorical_columns)

# -------------------------------
# CATEGORICAL VARIABLE ANALYSIS
# -------------------------------

for column in categorical_columns:
    print("\nColumn:", column)
    print("Unique values:")
    print(df[column].unique())

    print("\nValue counts:")
    print(df[column].value_counts())

# -------------------------------
# HISTOGRAMS
# -------------------------------

for column in numerical_columns:

    plt.figure(figsize=(8, 5))

    plt.hist(df[column], bins=30, edgecolor='black')

    plt.title("Histogram of " + column)
    plt.xlabel(column)
    plt.ylabel("Frequency")

    plt.show()

# -------------------------------
# BOXPLOTS
# -------------------------------

for column in numerical_columns:

    plt.figure(figsize=(8, 5))

    plt.boxplot(df[column].dropna())

    plt.title("Boxplot of " + column)
    plt.ylabel(column)

    plt.show()

# -------------------------------
# IQR OUTLIER DETECTION
# -------------------------------

# We check the main continuous numeric columns
# Success is a binary variable, so we don't treat it as a continuous
# outlier variable.

outlier_columns = ['Attendees', 'Expenses']

for column in outlier_columns:

    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)

    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outliers = df[
        (df[column] < lower_bound) |
        (df[column] > upper_bound)
    ]

    print("\nColumn:", column)
    print("Q1:", Q1)
    print("Q3:", Q3)
    print("IQR:", IQR)
    print("Lower Bound:", lower_bound)
    print("Upper Bound:", upper_bound)
    print("Number of outliers:", len(outliers))

# -------------------------------
# REMOVE OUTLIERS USING IQR
# -------------------------------

df_clean = df.copy()

for column in outlier_columns:

    Q1 = df_clean[column].quantile(0.25)
    Q3 = df_clean[column].quantile(0.75)

    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    df_clean = df_clean[
        (df_clean[column] >= lower_bound) &
        (df_clean[column] <= upper_bound)
    ]

print("Original number of rows:", len(df))
print("Rows after outlier removal:", len(df_clean))
print("Rows removed:", len(df) - len(df_clean))

# -------------------------------
# MISSING VALUES AFTER OUTLIER REMOVAL
# -------------------------------

print("Missing values before imputation:")

display(df_clean.isnull().sum())

# -------------------------------
# MEAN VS MEDIAN
# -------------------------------

for column in numerical_columns:

    mean_value = df_clean[column].mean()
    median_value = df_clean[column].median()

    print("\nColumn:", column)
    print("Mean:", mean_value)
    print("Median:", median_value)
    print("Difference:", abs(mean_value - median_value))

# -------------------------------
# MEAN VS MEDIAN VISUALIZATION
# -------------------------------

for column in ['Attendees', 'Expenses']:

    mean_value = df_clean[column].mean()
    median_value = df_clean[column].median()

    plt.figure(figsize=(8, 5))

    plt.hist(df_clean[column], bins=30, edgecolor='black')

    plt.axvline(mean_value, linestyle='--', linewidth=2, label='Mean')
    plt.axvline(median_value, linestyle='-', linewidth=2, label='Median')

    plt.title("Mean vs Median - " + column)
    plt.xlabel(column)
    plt.ylabel("Frequency")
    plt.legend()

    plt.show()

# -------------------------------
# MEDIAN IMPUTATION
# -------------------------------

for column in numerical_columns:

    median_value = df_clean[column].median()

    df_clean[column] = df_clean[column].fillna(median_value)

print("Median imputation completed!")

# -------------------------------
# CATEGORICAL IMPUTATION
# -------------------------------

for column in categorical_columns:

    mode_value = df_clean[column].mode()[0]

    df_clean[column] = df_clean[column].fillna(mode_value)

    print(column, "missing values replaced with:", mode_value)

# -------------------------------
# FINAL MISSING VALUE CHECK
# -------------------------------

print("Missing values after imputation:")

display(df_clean.isnull().sum())

# -------------------------------
# FINAL DUPLICATE CHECK
# -------------------------------

print("Duplicate rows after cleaning:", df_clean.duplicated().sum())

# -------------------------------
# FINAL DATASET PROFILE
# -------------------------------

print("FINAL DATASET PROFILE")
print("----------------------")

print("Number of rows:", df_clean.shape[0])
print("Number of columns:", df_clean.shape[1])

print("\nColumn names:")
print(df_clean.columns.tolist())

print("\nData types:")
print(df_clean.dtypes)

print("\nMissing values:")
display(df_clean.isnull().sum())

print("\nDuplicate rows:")
print(df_clean.duplicated().sum())

print("\nFinal summary statistics:")
display(df_clean.describe())

# -------------------------------
# BEFORE VS AFTER CLEANING
# -------------------------------

comparison = pd.DataFrame({
    'Before Cleaning': [
        df.shape[0],
        df.shape[1],
        df.isnull().sum().sum(),
        df.duplicated().sum()
    ],

    'After Cleaning': [
        df_clean.shape[0],
        df_clean.shape[1],
        df_clean.isnull().sum().sum(),
        df_clean.duplicated().sum()
    ]
}, index=[
    'Number of Rows',
    'Number of Columns',
    'Total Missing Values',
    'Duplicate Rows'
])

display(comparison)

# -------------------------------
# SAVE CLEANED DATASET
# -------------------------------

df_clean.to_csv("final_dav_dataset_cleaned.csv", index=False)

print("Cleaned dataset saved successfully!")

# Download the cleaned CSV file to your computer

from google.colab import files

files.download("final_dav_dataset_cleaned.csv")